In [2]:
import torch
mask = torch.arange(3)
mask, mask[None, :].shape

(tensor([0, 1, 2]), torch.Size([1, 3]))

In [13]:
val = torch.tensor([1,2])
val[:, None].shape

torch.Size([2, 1])

In [18]:
m = mask[None, :] < val[:, None]
m

tensor([[ True, False, False],
        [ True,  True, False]])

In [16]:
X = torch.tensor([[1,2,3], [4,5,6]])

In [19]:
X[m] = 1

In [24]:
mask.dim()

1

In [25]:
queries, keys = torch.normal(0, 1, (2, 1, 2)), torch.ones((2, 10, 2))

In [26]:
queries, keys

(tensor([[[-0.4454, -0.3810]],
 
         [[ 0.6407, -0.5502]]]),
 tensor([[[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]]]))

In [30]:
torch.bmm(queries, keys.transpose(1, 2)).shape

torch.Size([2, 1, 10])

In [4]:
hidden_state = torch.rand([16, 4, 12])
hidden_state[-1].shape

torch.Size([4, 12])